# our base image
FROM fedora:22

RUN dnf install -y http://repos.halvm.org/fedora-22/x86_64/halvm-yum-repo-22-3.fc22.noarch.rpm && dnf update -y
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-HaLVM
RUN dnf install -y HaLVM-gmp vim tmux zsh git

VOLUME  /halvm
WORKDIR /halvm
