FROM halvm/base:fedora22

RUN halvm-cabal update && \
    halvm-cabal install cryptonite -f-integer-gmp && \
    halvm-cabal install hans && \
    halvm-cabal install network-hans

RUN git clone http://github.com/acw/HTTP    && \
    (cd HTTP && halvm-cabal install)        && \
    rm -rf HTTP


RUN dnf install -y ec2-unikernel
