FROM halvm/base:fedora24

RUN halvm-cabal update && \
    halvm-cabal install --global cryptonite -f-integer-gmp && \
    halvm-cabal install --global hans && \
    halvm-cabal install --global network-hans

RUN git clone http://github.com/acw/HTTP    && \
    (cd HTTP && halvm-cabal install --global)        && \
    rm -rf HTTP

RUN dnf install -y ec2-unikernel
