# our base image
FROM fedora:24

RUN dnf install -y http://repos.halvm.org/fedora-24/x86_64/halvm-yum-repo-24-3.fc24.noarch.rpm
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-HaLVM
RUN dnf install -y HaLVM vim tmux zsh git

VOLUME  /halvm
WORKDIR /halvm
